/*
Copyright 2018 The Kubernetes sample-controller Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// This file was automatically generated by informer-gen

package v1

import (
	time "time"

	alarmdefinition_v1 "github.com/monasca/alarm-definition-controller/pkg/apis/alarmdefinition/v1"
	versioned "github.com/monasca/alarm-definition-controller/pkg/client/clientset/versioned"
	internalinterfaces "github.com/monasca/alarm-definition-controller/pkg/client/informers/externalversions/internalinterfaces"
	v1 "github.com/monasca/alarm-definition-controller/pkg/client/listers/alarmdefinition/v1"
	meta_v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// AlarmDefinitionInformer provides access to a shared informer and lister for
// AlarmDefinitions.
type AlarmDefinitionInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.AlarmDefinitionLister
}

type alarmDefinitionInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewAlarmDefinitionInformer constructs a new informer for AlarmDefinition type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewAlarmDefinitionInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredAlarmDefinitionInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredAlarmDefinitionInformer constructs a new informer for AlarmDefinition type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredAlarmDefinitionInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options meta_v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.MonascaV1().AlarmDefinitions(namespace).List(options)
			},
			WatchFunc: func(options meta_v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.MonascaV1().AlarmDefinitions(namespace).Watch(options)
			},
		},
		&alarmdefinition_v1.AlarmDefinition{},
		resyncPeriod,
		indexers,
	)
}

func (f *alarmDefinitionInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredAlarmDefinitionInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *alarmDefinitionInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&alarmdefinition_v1.AlarmDefinition{}, f.defaultInformer)
}

func (f *alarmDefinitionInformer) Lister() v1.AlarmDefinitionLister {
	return v1.NewAlarmDefinitionLister(f.Informer().GetIndexer())
}
